# Generated by Django 5.2.4 on 2025-07-27 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=255, unique=True)),
                ('wallet_type', models.CharField(choices=[('custodial', 'Custodial'), ('non_custodial', 'Non-Custodial')], default='custodial', max_length=20)),
                ('storage_type', models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold')], default='hot', max_length=20)),
                ('chain_symbol', models.CharField(max_length=20, null=True)),
                ('network_type', models.CharField(max_length=20, null=True)),
                ('wallet_format', models.CharField(max_length=50, null=True)),
                ('address_index', models.CharField(max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField(null=True)),
                ('key_format', models.CharField(default='base64', max_length=20)),
                ('encryption_iv', models.CharField(max_length=255, null=True)),
                ('encryption_algorithm', models.CharField(default='AES-256', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('derivation_path', models.CharField(max_length=255, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet')),
            ],
            options={
                'db_table': 'key_pair',
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['id', 'wallet_address'], name='wallet_id_6bc27c_idx'),
        ),
        migrations.AddIndex(
            model_name='keypair',
            index=models.Index(fields=['id', 'wallet'], name='key_pair_id_ace50a_idx'),
        ),
        migrations.AddConstraint(
            model_name='keypair',
            constraint=models.UniqueConstraint(fields=('wallet', 'public_key', 'private_key'), name='unique-wallet-keys'),
        ),
    ]
