# Generated by Django 5.2.4 on 2025-07-27 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='chain_symbol',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='network_type',
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('chain_symbol', models.CharField(max_length=20, unique=True)),
                ('network', models.CharField(max_length=20, null=True)),
                ('chain_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'blockchain_network',
                'indexes': [models.Index(fields=['id', 'name'], name='blockchain__id_21c001_idx'), models.Index(fields=['chain_symbol'], name='blockchain__chain_s_efd7a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'chain_symbol'), name='unique_network_name_chain_symbol')],
            },
        ),
        migrations.AddField(
            model_name='wallet',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallets.blockchainnetwork'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('wallet_address', 'chain'), name='unique_wallet_on_chain'),
        ),
    ]
