# Generated by Django 5.2.4 on 2025-08-10 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_blockchainnetwork_network_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='unique_wallet_on_chain',
        ),
        migrations.RemoveIndex(
            model_name='wallet',
            name='wallet_id_6bc27c_idx',
        ),
        migrations.RemoveField(
            model_name='keypair',
            name='encryption_algorithm',
        ),
        migrations.RemoveField(
            model_name='keypair',
            name='encryption_iv',
        ),
        migrations.RemoveField(
            model_name='keypair',
            name='key_format',
        ),
        migrations.AddField(
            model_name='keypair',
            name='additional_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['id', 'wallet_name', 'wallet_address'], name='wallet_id_8808bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('wallet_name', 'wallet_address', 'chain'), name='unique_wallet_on_chain'),
        ),
    ]
